version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: "Saturday"
      timezone: 'America/Denver'
    labels:
      - 'dependabot'
      - 'dependencies'
